[package]
name = "supapro-telegram"
version = "0.2.0"
authors = ["Alexander Zaitsev <zamazan4ik@tut.by>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "2.2.0"
actix-web = "3.3.2"
anyhow = "1.0.42"
chrono = "0.4.19"
log = "0.4.14"
once_cell = "1.8.0"
once-cell-regex = "0.2.1"
pretty_env_logger = "0.4.0"
regex = "1.5.4"
serde_json = "1.0.64"
teloxide = { version = "0.5.1", features = ["auto-send", "macros"] }
tokio = { version = "1.9.0", features = ["rt-multi-thread", "macros"] }
tokio-stream = "0.1.7"

[profile.release]
lto = true
