[package]
name = "supapro-telegram"
version = "0.1.0"
authors = ["Alexander Zaitsev <aliaaksandr.zaitsau@solarwinds.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "1.1.1"
actix-web = "3.2.0"
anyhow = "1.0.38"
chrono = "0.4.19"
log = "0.4.11"
once_cell = "1.5.1"
once-cell-regex = "0.2.0"
pretty_env_logger = "0.4.0"
regex = "1.4.2"
serde_json = "1.0.59"
teloxide = "0.3.4"
tokio = { version = "0.2.22", features = ["rt-threaded", "macros"] }

[profile.release]
lto = true
